AllCops:
    NewCops: enable
    TargetRubyVersion: 2.5

Layout/IndentationWidth:
    Width: 4

Layout/LineLength:
    Enabled: false

Naming/FileName:
    Enabled: false

Naming/RescuedExceptionsVariableName:
    PreferredName: exception

Style/FrozenStringLiteralComment:
    Enabled: false

Style/HashSyntax:
    EnforcedStyle: hash_rockets

Style/RaiseArgs:
    EnforcedStyle: compact

Style/RedundantBegin:
    Enabled: false

Style/Semicolon:
    AllowAsExpressionSeparator: true

Style/SymbolArray:
    Enabled: false

