matrix:
  include:
  - language: ruby
    name: Bundler (rvm 2.6)
    rvm: 2.6
    before_install:
    - gem install bundler
  - language: ruby
    name: Bundler (rvm 2.7)
    rvm: 2.7
    before_install:
    - gem install bundler
  - language: ruby
    name: Bundler (rvm 3.0)
    rvm: 3.0
    before_install:
    - gem install bundler
  - language: ruby
    name: Rubocop (rvm 2.6)
    rvm: 2.6
    before_install:
    - git clone https://github.com/TravisToolbox/rubocop.git
    install:
    - "./rubocop/install.sh"
    script:
    - "./rubocop/scan.sh"
  - language: ruby
    name: Rubocop (rvm 2.7)
    rvm: 2.7
    before_install:
    - git clone https://github.com/TravisToolbox/rubocop.git
    install:
    - "./rubocop/install.sh"
    script:
    - "./rubocop/scan.sh"
  - language: ruby
    name: Rubocop (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/rubocop.git
    install:
    - "./rubocop/install.sh"
    script:
    - "./rubocop/scan.sh"
  - language: ruby
    name: Reek (rvm 2.6)
    rvm: 2.6
    before_install:
    - git clone https://github.com/TravisToolbox/reek.git
    install:
    - "./reek/install.sh"
    script:
    - "./reek/scan.sh"
  - language: ruby
    name: Reek (rvm 2.7)
    rvm: 2.7
    before_install:
    - git clone https://github.com/TravisToolbox/reek.git
    install:
    - "./reek/install.sh"
    script:
    - "./reek/scan.sh"
  - language: ruby
    name: Reek (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/reek.git
    install:
    - "./reek/install.sh"
    script:
    - "./reek/scan.sh"
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md,github-lister-core.gemspec"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: WrtNQR+lIRR6medI5hAMTJuFgzTduHhG5AplB7Hea85Ud9SggDDJdqlLzltO7bzMwSR4kVJzOFirdRpqpF5ZOyAm7+SWI1JHilPJeLQ0YA68mdao+vX9b6zSjxzcSRfBZuet3X82j0hmqEeEqVWe/Zf8r7uSGJUCx9ulxHEGu8LAw7rFuyf8XpP51R9g3A6OmFiV8DaFOH+8SMOK4zeBWOeqrnTXgYrFfzGYPOj/NruSiSTH/LSLYw6SfLcu4+vjQ0MeD7W9hMbpsvdtv+i27qbzrqoG11JkHUGym5SVkERErbg6M3UIM1qkKqpgBuem+eT9DkZP8pyaCNmWTQjo/b3yGtL8Ny3pX/xkTrhxWsOKiCVqHpeO1s4VYIDTCl68gAcYg9Y+je39k2kiUrwN3ksuEtYUvWzIdcoekKUbDQLJc6cMK4jD4DTugPHmXQCpmwVA59aeihGdzEUKFSIis4/hV5SNpsOOmzt5fcTsMRJFY9Jza/DxsLOnsHfqsktCIfXHCz3Loto+v+xVykn50lTitTDcGrl0gqBRa96sma45PmvJrvS8Ep6uLNhxzqnqcc687fmg4MQACfHr1G9lyXt9/UWovGDRAudbolH3RWWU04OHSJcJq0i/UP3FxHbdjnDxXbV1qyDb41O1bpHDSCfyV2GEknr/H2UDK81VXU0=
